hydra:
  job:
    chdir: false
output_file: coco_train/retrieved.json
num_candidates: 50
num_ice: 1
task_name: coco
model_name: 'openai/clip-vit-large-patch14'
batch_size: 128                  # the batch size when running encoding
faiss_index: coco_train/large_coco.index

# parameters needed to initialize the input dataset
dataset_reader:
  _target_: src.dataset_readers.base_dsr.BaseDatasetReader
  task_name: ${task_name}
  model_name: ${model_name}
  field: q
  dataset_split: train          # one of `dataset_path` and `dataset_split` must be set
  dataset_path: null
  ds_size: 5000

# parameters needed to initialize the index_reader
index_reader:
  _target_: src.dataset_readers.index_dsr.IndexDatasetReader
  task_name: ${task_name}
  model_name: ${model_name}
  field: qa
  dataset_split: train   # one of `dataset_path` and `dataset_split` must be set
  dataset_path: coco_train/index_dataset.json
  ds_size: null

# parameters needed to initialize the bi-encoder model
model_config:
  _target_: src.models.biencoder.BiEncoderConfig
  q_model_name: ${model_name}
  ctx_model_name: ${model_name}
  norm_embed: true
